# Settings.yml

---
conf.py:
  copyright: 2018
  project: AWS System Information
  version: 1.0.0
  release: 1.0.0
  html_theme_options:
    github_repository: schams-net/aws_system_information
    github_branch: master
    t3install:
    - http://docs.typo3.org/typo3cms/InstallationGuide/
    - null
...
